name: flask_avito workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t one2q/skypro_flask:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push one2q/skypro_flask:$GITHUB_REF_NAME-$GITHUB_RUN_ID
